<?php $_sectors = $this->getSectors(); ?>
<?php $_sectorMapping = $this->getSectorMapping(); ?>
<div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__("Showare Sectors to SP Sectors") ?></h4>
</div>
<fieldset>
    <legend><?php echo $this->__("Sector Mapping") ?></legend>
    <span class="field-row">
        <label for="sec_a"><?php echo $this->__("SEC_A:") ?></label>
        <select id="sec_a" name="sec_a">
            <?php foreach ($_sectors as $_value) : ?>
                <option value="<?php echo $_value['sector']?>" <?php if($_sectorMapping['sec_a'] == $_value['sector']) :?> selected="selected" <?php endif; ?>><?php echo $_value['sector']?></option>
            <?php endforeach; ?>
        </select>
    </span>
    <span class="field-row">
        <label for="sec_b"><?php echo $this->__("SEC_B:") ?></label>
        <select id="sec_b" name="sec_b">
            <?php foreach ($_sectors as $_value) : ?>
                <option value="<?php echo $_value['sector']?>"<?php if($_sectorMapping['sec_b'] == $_value['sector']) :?> selected="selected" <?php endif; ?>><?php echo $_value['sector']?></option>
            <?php endforeach; ?>
        </select>
    </span>
    <span class="field-row">
        <label for="sec_c"><?php echo $this->__("SEC_C:") ?></label>
        <select id="sec_c" name="sec_c">
            <?php foreach ($_sectors as $_value) : ?>
                <option value="<?php echo $_value['sector']?>"<?php if($_sectorMapping['sec_c'] == $_value['sector']) :?> selected="selected" <?php endif; ?>><?php echo $_value['sector']?></option>
            <?php endforeach; ?>
        </select>
    </span>
</fieldset>